version: '3.8'

services: 
  koel:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - music:/music
      - covers:/var/www/html/public/img/covers
      - search_index:/var/www/html/storage/search-indexes

    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=koel
      - DB_USERNAME=koel
      - DB_PASSWORD=koel

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=koel
      - MYSQL_DATABASE=koel
      - MYSQL_USER=koel
      - MYSQL_PASSWORD=koel

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  
  phpmyadmin:
    image: phpmyadmin:5.2-fpm-alpine
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=koel
      - PMA_PASSWORD=koel
    depends_on:
      - db

volumes:
  mariadb-data:
  music:
  covers:
  search_index: