version: '3.8'

services: 
  koel:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - music:/music
      - covers:/var/www/html/public/img/covers
      - search_index:/var/www/html/storage/search-indexes
    ports:
      - "80:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=koel
      - DB_USERNAME=koel
      - DB_PASSWORD=koel
    networks:
      - app-network

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=koel
      - MYSQL_DATABASE=koel
      - MYSQL_USER=koel
      - MYSQL_PASSWORD=koel
    networks:
      - app-network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2-fpm-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=koel
      - PMA_PASSWORD=koel
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mariadb-data:
  music:
  covers:
  search_index:

networks:
  app-network:
    driver: bridge
