#!/bin/bash

set -e

# Change to program root directory.
cd /var/www/html

# Run the next entrypoint in the chain.
echo "running docker-php-entrypoint with arguments $@"
docker-php-entrypoint $@

# Run Laravel migrations
 php artisan migrate --force
# php artisan db:seed